export interface City {
  id: string
  name: string
  region?: string
}

export const cities: City[] = [
  { id: "global", name: "Global" },
  { id: "turkiye", name: "Tüm Türkiye" },
  { id: "istanbul", name: "İstanbul (Tümü)" },
  { id: "istanbul-asia", name: "İstanbul (Asya)", region: "İstanbul" },
  { id: "istanbul-europe", name: "İstanbul (Avrupa)", region: "İstanbul" },
  { id: "adana", name: "Adana" },
  { id: "adiyaman", name: "Adıyaman" },
  { id: "afyon", name: "Afyonkarahisar" },
  { id: "ankara", name: "Ankara" },
  { id: "antalya", name: "Antalya" },
  { id: "aydin", name: "Aydın" },
  { id: "balikesir", name: "Balıkesir" },
  { id: "bolu", name: "Bolu" },
  { id: "bursa", name: "Bursa" },
  { id: "canakkale", name: "Çanakkale" },
  { id: "corum", name: "Çorum" },
  { id: "denizli", name: "Denizli" },
  { id: "diyarbakir", name: "Diyarbakır" },
  { id: "duzce", name: "Düzce" },
  { id: "edirne", name: "Edirne" },
  { id: "elazig", name: "Elazığ" },
  { id: "eskisehir", name: "Eskişehir" },
  { id: "gaziantep", name: "Gaziantep" },
  { id: "giresun", name: "Giresun" },
  { id: "hatay", name: "Hatay" },
  { id: "isparta", name: "Isparta" },
  { id: "izmir", name: "İzmir" },
  { id: "kahramanmaras", name: "Kahramanmaraş" },
  { id: "karabuk", name: "Karabük" },
  { id: "kars", name: "Kars" },
  { id: "kastamonu", name: "Kastamonu" },
  { id: "kayseri", name: "Kayseri" },
  { id: "kirklareli", name: "Kırklareli" },
  { id: "konya", name: "Konya" },
  { id: "kutahya", name: "Kütahya" },
  { id: "malatya", name: "Malatya" },
  { id: "manisa", name: "Manisa" },
  { id: "mardin", name: "Mardin" },
  { id: "mersin", name: "Mersin" },
  { id: "mugla", name: "Muğla" },
  { id: "ordu", name: "Ordu" },
  { id: "osmaniye", name: "Osmaniye" },
  { id: "sakarya", name: "Sakarya" },
  { id: "samsun", name: "Samsun" },
  { id: "sivas", name: "Sivas" },
  { id: "tekirdag", name: "Tekirdağ" },
  { id: "tokat", name: "Tokat" },
  { id: "trabzon", name: "Trabzon" },
  { id: "usak", name: "Uşak" },
  { id: "van", name: "Van" },
  { id: "yalova", name: "Yalova" },
  { id: "zonguldak", name: "Zonguldak" },
]

